### ISSUE TITLE
cmdlets not imported

### ISSUE THREAD

**Issue by bkeeler** [Persistent13/PS.B2#7]
Apologies if I'm doing something wrong, I'm a powershell n00b. But I don't get any cmdlets imported it seems. The import statement runs without error, as did the installation, so I assume the install went well.

PS C:\Users\kitchen> import-module PS.B2

PS C:\Users\kitchen> Connect-B2Cloud "foo", "bar"
Connect-B2Cloud : The term 'Connect-B2Cloud' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
- Connect-B2Cloud "foo", "bar"
- ~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (Connect-B2Cloud:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\kitchen> (Get-Module PS.B2).ExportedCommands.Keys

PS C:\Users\kitchen> $Host

Name             : Windows PowerShell ISE Host
Version          : 4.0
InstanceId       : 038ca877-8316-4480-9c98-3195daf9a1f1
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.Host.ISE.ISEOptions
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by Persistent13** [comment]
Hi @bkeeler

If you delete the module and re-install it you should not have any issues.
The importing was buggered a while back and I've been meaning to release the fix.

**Comment by Persistent13** [comment]
I'm closing the issue for now, let me know if you still need help!
